<?php
/**
 * LegLocationType
 *
 * PHP version 5
 *
 * @category Class
 * @package  COS\Swagger
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
* COS API
 *
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
* OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.4
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace COS\Swagger\Model;
use \COS\Swagger\ObjectSerializer;

/**
 * LegLocationType Class Doc Comment
 *
 * @category Class
 * @description LegLocationType represents a type of a location that takes part in a delivery.
 * @package  COS\Swagger
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LegLocationType
{
    /**
     * Possible values of this enum
     */
    const UNKNOWN = 'UNKNOWN';
const WAREHOUSE = 'WAREHOUSE';
const STORE = 'STORE';
const HOME = 'HOME';
const PICKUP = 'PICKUP';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNKNOWN,
self::WAREHOUSE,
self::STORE,
self::HOME,
self::PICKUP,        ];
    }
}
